### ISSUE TITLE
How to handle the TODOs?

### ISSUE THREAD

**Issue by drpaneas** [redhat-appstudio/managed-gitops#56]
I have noticed that our code has several `// TODO:` entries. 

```shell
$ git grep "// TODO:" | wc -l
      87
```

Are we capturing them in a project board somewhere? If not, there is this [TODO Bot](https://todo.jasonet.co/) which I am using with the following config:

```yaml
# Integrate todo bot (https://github.com/probot/probot)
# https://todo.jasonet.co/
todo:
  keyword: ["@todo", "TODO"] # string|string[]
  bodyKeyword: ["@body", "BODY"] # string|string[]
  blobLines: 5                # number|boolean, 0 or false to disable
  autoAssign: true            # string|string[]|boolean
  label: true                 # boolean|string|string[]
  reopenClosed: false         # boolean
```

This one creates a GitHub issue for every `TODO` entry in the code, used mostly as a reminder.
It works great. If you would like this approach you need to install it, as I do not have permissions to "install" integrations in this repo.
