### ISSUE TITLE
Implement Argo CD Load Test

### ISSUE THREAD

**Issue by jgwest** [redhat-appstudio/managed-gitops#8]
In order to allow us to decide how much memory/CPU to provision to give to Argo CD, we need to create a load test that uses Argo CD to create a bunch of cluster resources.

Create a Go unit test that does the following:
-  Spins up 1 Argo CD instance (by following the Argo CD install instructions), then waits for it to be installed (all expected resources are running).
    - Probably the easiest way to spin up an Argo CD instance from inside Go is to call `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml` using [golang's os Exec function](https://pkg.go.dev/os/exec).
- Next, it adds new Applications to Argo CD (by creating the `Application` CR within the Argo CD namespace)
    - For examples of interaction with Kubernetes client API, see what we do in ApplicationSet repo. Search for uses of `argov1alpha1.Application`
- This will require us to find real world applications that we can use to test this.  
    - See https://github.com/argoproj/argo-cd/issues/4392 for 3 examples. 
    - See https://github.com/redhat-cop/gitops-catalog for more examples (but say away from the ones that require OpenShift)
- Use large applications like the prometheus operator, not tiny applications like the guestbook. For an example of a large application, apply the following in the namespace:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jgw-prometheus
  namespace: argocd
spec:
  destination:
    namespace: jgw
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      version: v2
    path: appset-examples/cluster-addon/prometheus-operator
    repoURL: https://github.com/jgwest/argocd-example-apps.git
```
- Determine pass/validation criteria (what does it mean for a load test to pass? no pod restarts?), and implement within test itself
- For, use applications that do not require OpenShift (for example, no openshift-specific operators)

See https://github.com/redhat-appstudio/managed-gitops/tree/main/utilities/load-test for barebones project to get started from.

The test should be its own standalone module under `https://github.com/redhat-appstudio/managed-gitops/utilities/load-test`. Why? Because it is likely to be useful by other projects (gitops operator, argo cd upstream), and keeping it separate makes this easy. (At a future time we might move it into its own repo)

See here for my previous (outdated) thoughts on how this would look: https://issues.redhat.com/browse/GITOPS-895
